version: "3"
services:
  zookeeper:
    image: jplock/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  solr1:
    hostname: solr1
    image: solr:latest
    ports:
      - "8983:8983"
    links:
      - "zookeeper:ZK"
    command: "bash -c '/opt/solr/bin/solr start -f -z zookeeper:2181'"
  solr2:
    hostname: solr2
    image: solr:latest
    ports:
      - "8984:8983"
    links:
      - "zookeeper:ZK"
    command: "bash -c '/opt/solr/bin/solr start -f -z zookeeper:2181'"
  nifi:
    hostname: nifi
    image: apache/nifi:${nifi.version}
    container_name: nifi
    ports:
      - 8080:8080
    links:
      - solr1
      - solr2
      - nifi2
    volumes:
      - /tmp/nifi:/opt/nifi_in
      - ./extensions:/opt/nifi/nifi-current/extensions
  nifi2:
    hostname: nifi2
    container_name: nifi2
    image: "apache/nifi:${nifi.version}"
    environment:
      - NIFI_WEB_HTTP_HOST=nifi2
      - NIFI_WEB_HTTP_PORT=9999
      - NIFI_REMOTE_INPUT_HOST=nifi2
    ports:
      - 9999:9999
    links:
      - solr1
      - solr2
