version: '3'
services:
  ldap:
    hostname: ldap
    container_name: ldap
    image: mikerthomsen/apacheds-docker-for-nifi
    ports:
      - "389:10389"
    volumes:
      - /opt/odp/ldap:/opt/odp/ldap:ro
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana
    environment:
      - "elasticsearch.username=elastic"
      - "elasticsearch.password=changeme"
    ports:
      - 5601:5601
    links:
      - elasticsearch
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /opt/nifi_demo/mongo-data:/data
      - /opt/nifi_demo/mongo:/opt/nifi_demo
  nifi:
    hostname: demo.nifi
    image: apache/nifi:${nifi.version}
    container_name: nifi
    environment:
      - AUTH=ldap
      - KEYSTORE_PATH=/opt/demo.nifi/keystore.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=U8khkCbNJKMyXFGyftAhv0Fg/qQrTsXH8VYQpglz1uo
      - TRUSTSTORE_PATH=/opt/demo.nifi/truststore.jks
      - TRUSTSTORE_PASSWORD=sh4TaEf9uqMMkq+A5XPIWraNPQVPv9HMdsHMmkD2iLw
      - TRUSTSTORE_TYPE=JKS
      - INITIAL_ADMIN_IDENTITY=CN=initialAdmin, OU=NiFi
      - LDAP_AUTHENTICATION_STRATEGY=SIMPLE
      - LDAP_MANAGER_DN=uid=admin,ou=system
      - LDAP_MANAGER_PASSWORD=secret
      - LDAP_USER_SEARCH_BASE=ou=people,dc=nifi,dc=com
      - LDAP_USER_SEARCH_FILTER=uid={0}
      - LDAP_IDENTITY_STRATEGY=USE_USERNAME
      - LDAP_URL=ldap://ldap:10389
      - NIFI_WEB_HTTP_HOST=demo.nifi
      - NIFI_WEB_HTTP_PORT=8888
    ports:
      - 8080:8080
      - 443:8443
    links:
      - ldap
      - elasticsearch
      - mongo
      - nifi2
      - postgres
    volumes:
      - /tmp/nifi:/opt/nifi_in
      - ./security_output/demo.nifi:/opt/demo.nifi
  nifi2:
    hostname: nifi2
    container_name: nifi2
    image: "apache/nifi:${nifi.version}"
    environment:
      - NIFI_WEB_HTTP_HOST=nifi2
      - NIFI_WEB_HTTP_PORT=9999
      - NIFI_REMOTE_INPUT_HOST=nifi2
    ports:
      - 9999:9999
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
