version: '3'
services:
  roach1:
    hostname: roach1
    image: cockroachdb/cockroach
    container_name: roach1
    ports:
      - 26257:26257
      - 8880:8080
    command: start --insecure
  roach2:
    hostname: roach2
    image: cockroachdb/cockroach
    container_name: roach2
    links:
      - roach1
    command: start --insecure --join=roach1
  roach3:
    hostname: roach3
    image: cockroachdb/cockroach
    container_name: roach3
    links:
      - roach1
    command: start --insecure --join=roach1
  nifi:
    hostname: nifi
    image: apache/nifi:${nifi.version}
    container_name: nifi
    ports:
      - 8080:8080
    links:
      - roach1
      - roach2
      - roach3
      - nifi2
    volumes:
      - /tmp/nifi:/opt/nifi_in
      - ./extensions:/opt/nifi/nifi-current/extensions
  nifi2:
    hostname: nifi2
    container_name: nifi2
    image: "apache/nifi:${nifi.version}"
    environment:
      - NIFI_WEB_HTTP_HOST=nifi2
      - NIFI_WEB_HTTP_PORT=9999
      - NIFI_REMOTE_INPUT_HOST=nifi2
    ports:
      - 9999:9999

