version: "3.0"
services:
  nifi:
    image: apache/nifi:${nifi.version}
    container_name: ignite_nifi
    ports:
      - 8080:8080
    links:
      - ignite
    volumes:
      - ./extensions:/opt/nifi/nifi-current/extensions
  ignite:
    image: apacheignite/ignite:${ignite.version}
    container_name: ignite
    ports:
      - 10800:10800
      - 11211:11211
      - 47100:47100
      - 47500:47500
