version: "3.1"
services:
  postgres:
    image: postgres:${postgres.version}
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
  nifi:
    hostname: nifi
    image: apache/nifi:${nifi.version}
    container_name: nifi
    ports:
      - 8080:8080
    links:
      - postgres
    volumes:
      - /tmp/nifi:/opt/nifi_in
      - ./extensions:/opt/nifi/nifi-current/extensions